site_name: Test Docs

plugins:
  - search
  - title-casing

nav:
  - home: page1.md # Home
  - section1: # Section1
      - a page: page2.md # A Page
      - "": # no warning
          - page3.md # no warning
  - "": page4.md # no warning
  - "": "https://127.0.0.1" # no warning
  - home ip: "https://127.0.0.1" # Home Ip
