site_name: Test Docs

plugins:
  - search
  - title-casing

nav:
  - home: page1.md # Home
  - section1: # Warning
      - a page: page2.md # Warning
      - "": # No Warning
          - page3.md # Warning
  - "": page4.md # No Warning
  - "": "https://127.0.0.1" # No Warning
  - home ip: "https://127.0.0.1" # Warning
